using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using PJDev.DevelopKit.BasicTemplate.Runtime;
using UnityEditor;
using UnityEngine;

namespace PJDev.DevelopKit.BasicTemplate.Editors
{
    public static class CDebugTagEnumGenerator
    {
        private const string DefaultTagName = "Default";

        public static bool TryValidateNewTag(IReadOnlyList<string> existingTags, string tagName,
            out string normalized, out string error)
        {
            if (!TryNormalizeTagName(tagName, out normalized, out error))
                return false;

            if (existingTags.Contains(normalized))
            {
                error = $"'{normalized}' 태그가 이미 존재합니다.";
                return false;
            }

            return true;
        }

        public static void ApplyAndGenerate(CDebugTagDefinitions definitions, IReadOnlyList<string> tags)
        {
            definitions.SetTags(tags);
            EditorUtility.SetDirty(definitions);
            Generate(definitions);
            AssetDatabase.SaveAssets();
        }

        public static void Generate(CDebugTagDefinitions definitions)
        {
            definitions.EnsureDefaultTagFirst();
            EditorUtility.SetDirty(definitions);
            WriteEnumFile(definitions.Tags);
            CDebugConsoleNavigationGenerator.Generate();
        }

        public static void Generate(IReadOnlyList<string> tags)
        {
            WriteEnumFile(NormalizeTags(tags));
        }

        private static List<string> NormalizeTags(IReadOnlyList<string> source)
        {
            var tags = source?
                .Where(tag => !string.IsNullOrWhiteSpace(tag))
                .Select(tag => tag.Trim())
                .Distinct()
                .ToList() ?? new List<string>();

            if (!tags.Contains(DefaultTagName))
                tags.Insert(0, DefaultTagName);

            return tags;
        }

        private static void WriteEnumFile(IReadOnlyList<string> sourceTags)
        {
            var tags = NormalizeTags(sourceTags);

            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated by CDebugTagEnumGenerator>");
            builder.AppendLine("// Do not edit manually.");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.BasicTemplate.Runtime");
            builder.AppendLine("{");
            builder.AppendLine("    public enum CDebugTag");
            builder.AppendLine("    {");

            for (int i = 0; i < tags.Count; i++)
                builder.AppendLine($"        {tags[i]} = {i},");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            var enumPath = CDebugPaths.EnumFilePath;
            var content = builder.ToString();
            if (File.Exists(enumPath) && File.ReadAllText(enumPath) == content)
                return;

            File.WriteAllText(enumPath, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(enumPath);
        }

        public static bool TryNormalizeTagName(string tagName, out string normalized, out string error)
        {
            normalized = tagName?.Trim();
            error = null;

            if (string.IsNullOrEmpty(normalized))
            {
                error = "태그 이름을 입력해 주세요.";
                return false;
            }

            if (!IsValidIdentifier(normalized))
            {
                error = "태그 이름은 C# 식별자 형식이어야 합니다. (예: Network, SceneLoad)";
                return false;
            }

            return true;
        }

        private static bool IsValidIdentifier(string name)
        {
            if (string.IsNullOrEmpty(name))
                return false;

            if (!(char.IsLetter(name[0]) || name[0] == '_'))
                return false;

            for (int i = 1; i < name.Length; i++)
            {
                char c = name[i];
                if (!char.IsLetterOrDigit(c) && c != '_')
                    return false;
            }

            return true;
        }
    }
}
