using System.IO;
using System.Text;
using UnityEditor;

namespace PJDev.DevelopKit.BasicTemplate.Editors
{
    /// <summary>CDebug 콘솔 더블클릭 시 호출부로 이동하는 Editor 스크립트를 생성합니다.</summary>
    public static class CDebugConsoleNavigationGenerator
    {
        public const string GeneratedFileName = "CDebugConsoleNavigation.Generated.cs";

        public static void Generate()
        {
            string directory = CDebugPaths.EditorGeneratedFolder;
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            string path = CDebugPaths.ConsoleNavigationGeneratedFilePath;
            string content = BuildSource();
            if (File.Exists(path) && File.ReadAllText(path) == content)
                return;

            File.WriteAllText(path, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(path);
        }

        private static string BuildSource()
        {
            var builder = new StringBuilder();

            builder.AppendLine("// <auto-generated by CDebugConsoleNavigationGenerator>");
            builder.AppendLine("// Do not edit manually.");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using System.IO;");
            builder.AppendLine("using System.Reflection;");
            builder.AppendLine("using System.Text.RegularExpressions;");
            builder.AppendLine("using UnityEditor;");
            builder.AppendLine("using UnityEditor.Callbacks;");
            builder.AppendLine("using UnityEditorInternal;");
            builder.AppendLine("using UnityEditor.PackageManager;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine("using PackageInfo = UnityEditor.PackageManager.PackageInfo;");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.BasicTemplate.Editors.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class CDebugConsoleNavigationGenerated");
            builder.AppendLine("    {");
            builder.AppendLine("        private const string LoggerScriptFileName = \"CDebug.cs\";");
            builder.AppendLine();
            builder.AppendLine("        private static readonly Regex StackTraceRegex = new(");
            builder.AppendLine("            @\"\\(at\\s+(.+?):(\\d+)\\)\",");
            builder.AppendLine("            RegexOptions.IgnoreCase | RegexOptions.Compiled);");
            builder.AppendLine();
            builder.AppendLine("        private static readonly string ProjectRoot =");
            builder.AppendLine("            Directory.GetParent(Application.dataPath)?.FullName;");
            builder.AppendLine();

            builder.AppendLine("        [OnOpenAsset(0)]");
            builder.AppendLine("#if UNITY_6000_2_OR_NEWER");
            builder.AppendLine("        public static bool OnOpenAsset(EntityId instanceID, int line)");
            builder.AppendLine("#else");
            builder.AppendLine("        public static bool OnOpenAsset(int instanceID, int line)");
            builder.AppendLine("#endif");
            builder.AppendLine("        {");
            builder.AppendLine("#if UNITY_6000_2_OR_NEWER");
            builder.AppendLine("            UnityEngine.Object target =");
            builder.AppendLine("                EditorUtility.EntityIdToObject(instanceID);");
            builder.AppendLine("#else");
            builder.AppendLine("            UnityEngine.Object target =");
            builder.AppendLine("                EditorUtility.InstanceIDToObject(instanceID);");
            builder.AppendLine("#endif");
            builder.AppendLine();
            builder.AppendLine("            if (!IsCDebugScript(target))");
            builder.AppendLine("                return false;");
            builder.AppendLine();
            builder.AppendLine("            string stackTrace = GetConsoleStackTrace();");
            builder.AppendLine("            if (string.IsNullOrEmpty(stackTrace))");
            builder.AppendLine("                return false;");
            builder.AppendLine();
            builder.AppendLine("            return TryOpenCallerFromStackTrace(stackTrace);");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine("        private static bool IsCDebugScript(UnityEngine.Object target)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (target == null)");
            builder.AppendLine("                return false;");
            builder.AppendLine();
            builder.AppendLine("            string assetPath = AssetDatabase.GetAssetPath(target);");
            builder.AppendLine();
            builder.AppendLine("            return !string.IsNullOrEmpty(assetPath)");
            builder.AppendLine("                   && string.Equals(");
            builder.AppendLine("                       Path.GetFileName(assetPath),");
            builder.AppendLine("                       LoggerScriptFileName,");
            builder.AppendLine("                       StringComparison.OrdinalIgnoreCase);");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine("        private static bool TryOpenCallerFromStackTrace(string stackTrace)");
            builder.AppendLine("        {");
            builder.AppendLine("            MatchCollection matches = StackTraceRegex.Matches(stackTrace);");
            builder.AppendLine();
            builder.AppendLine("            for (int i = 0; i < matches.Count; i++)");
            builder.AppendLine("            {");
            builder.AppendLine("                Match match = matches[i];");
            builder.AppendLine("                if (!match.Success)");
            builder.AppendLine("                    continue;");
            builder.AppendLine();
            builder.AppendLine("                string path = match.Groups[1].Value");
            builder.AppendLine("                    .Trim()");
            builder.AppendLine("                    .Trim('\"')");
            builder.AppendLine("                    .Replace('\\\\', '/');");
            builder.AppendLine();
            builder.AppendLine("                if (string.Equals(");
            builder.AppendLine("                        Path.GetFileName(path),");
            builder.AppendLine("                        LoggerScriptFileName,");
            builder.AppendLine("                        StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("                {");
            builder.AppendLine("                    continue;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                if (!int.TryParse(");
            builder.AppendLine("                        match.Groups[2].Value,");
            builder.AppendLine("                        out int callerLine))");
            builder.AppendLine("                {");
            builder.AppendLine("                    continue;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                string fullPath = BuildFullPath(path);");
            builder.AppendLine();
            builder.AppendLine("                if (string.IsNullOrEmpty(fullPath)");
            builder.AppendLine("                    || !File.Exists(fullPath))");
            builder.AppendLine("                {");
            builder.AppendLine("                    continue;");
            builder.AppendLine("                }");
            builder.AppendLine();
            builder.AppendLine("                InternalEditorUtility.OpenFileAtLineExternal(");
            builder.AppendLine("                    fullPath,");
            builder.AppendLine("                    callerLine);");
            builder.AppendLine();
            builder.AppendLine("                return true;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine("        private static string BuildFullPath(string path)");
            builder.AppendLine("        {");
            builder.AppendLine("            if (string.IsNullOrEmpty(path))");
            builder.AppendLine("                return null;");
            builder.AppendLine();
            builder.AppendLine("            // 이미 Library/PackageCache 등을 포함하는 절대 경로.");
            builder.AppendLine("            if (Path.IsPathRooted(path))");
            builder.AppendLine("                return path;");
            builder.AppendLine();
            builder.AppendLine("            if (string.IsNullOrEmpty(ProjectRoot))");
            builder.AppendLine("                return null;");
            builder.AppendLine();
            builder.AppendLine("            // 프로젝트 내부 일반 스크립트 경로.");
            builder.AppendLine("            if (path.StartsWith(");
            builder.AppendLine("                    \"Assets/\",");
            builder.AppendLine("                    StringComparison.OrdinalIgnoreCase)");
            builder.AppendLine("                || path.StartsWith(");
            builder.AppendLine("                    \"Library/\",");
            builder.AppendLine("                    StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("            {");
            builder.AppendLine("                return Path.Combine(ProjectRoot, path);");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            // Unity 패키지 가상 경로.");
            builder.AppendLine("            if (path.StartsWith(");
            builder.AppendLine("                    \"Packages/\",");
            builder.AppendLine("                    StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("            {");
            builder.AppendLine("                return ResolvePackagePath(path);");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            // 경로 앞에 프로젝트명 등이 붙은 경우.");
            builder.AppendLine("            int assetsIndex = path.IndexOf(");
            builder.AppendLine("                \"Assets/\",");
            builder.AppendLine("                StringComparison.OrdinalIgnoreCase);");
            builder.AppendLine();
            builder.AppendLine("            if (assetsIndex >= 0)");
            builder.AppendLine("            {");
            builder.AppendLine("                return Path.Combine(");
            builder.AppendLine("                    ProjectRoot,");
            builder.AppendLine("                    path.Substring(assetsIndex));");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            int packagesIndex = path.IndexOf(");
            builder.AppendLine("                \"Packages/\",");
            builder.AppendLine("                StringComparison.OrdinalIgnoreCase);");
            builder.AppendLine();
            builder.AppendLine("            if (packagesIndex >= 0)");
            builder.AppendLine("            {");
            builder.AppendLine("                return ResolvePackagePath(");
            builder.AppendLine("                    path.Substring(packagesIndex));");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            int libraryIndex = path.IndexOf(");
            builder.AppendLine("                \"Library/\",");
            builder.AppendLine("                StringComparison.OrdinalIgnoreCase);");
            builder.AppendLine();
            builder.AppendLine("            if (libraryIndex >= 0)");
            builder.AppendLine("            {");
            builder.AppendLine("                return Path.Combine(");
            builder.AppendLine("                    ProjectRoot,");
            builder.AppendLine("                    path.Substring(libraryIndex));");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return Path.Combine(ProjectRoot, path);");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine("        private static string ResolvePackagePath(string packagePath)");
            builder.AppendLine("        {");
            builder.AppendLine("            PackageInfo packageInfo =");
            builder.AppendLine("                PackageInfo.FindForAssetPath(packagePath);");
            builder.AppendLine();
            builder.AppendLine("            if (packageInfo == null");
            builder.AppendLine("                || string.IsNullOrEmpty(packageInfo.resolvedPath)");
            builder.AppendLine("                || string.IsNullOrEmpty(packageInfo.assetPath))");
            builder.AppendLine("            {");
            builder.AppendLine("                return null;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            string packageAssetRoot = packageInfo.assetPath");
            builder.AppendLine("                .Replace('\\\\', '/')");
            builder.AppendLine("                .TrimEnd('/');");
            builder.AppendLine();
            builder.AppendLine("            if (!packagePath.StartsWith(");
            builder.AppendLine("                    packageAssetRoot,");
            builder.AppendLine("                    StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("            {");
            builder.AppendLine("                return null;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            string relativePath = packagePath");
            builder.AppendLine("                .Substring(packageAssetRoot.Length)");
            builder.AppendLine("                .TrimStart('/');");
            builder.AppendLine();
            builder.AppendLine("            return Path.Combine(");
            builder.AppendLine("                packageInfo.resolvedPath,");
            builder.AppendLine("                relativePath);");
            builder.AppendLine("        }");
            builder.AppendLine();

            builder.AppendLine("        private static string GetConsoleStackTrace()");
            builder.AppendLine("        {");
            builder.AppendLine("            Type consoleWindowType =");
            builder.AppendLine("                Type.GetType(\"UnityEditor.ConsoleWindow,UnityEditor\");");
            builder.AppendLine();
            builder.AppendLine("            if (consoleWindowType == null)");
            builder.AppendLine("                return string.Empty;");
            builder.AppendLine();
            builder.AppendLine("            FieldInfo consoleField = consoleWindowType.GetField(");
            builder.AppendLine("                \"ms_ConsoleWindow\",");
            builder.AppendLine("                BindingFlags.Static | BindingFlags.NonPublic);");
            builder.AppendLine();
            builder.AppendLine("            if (consoleField?.GetValue(null)");
            builder.AppendLine("                is not EditorWindow consoleWindow");
            builder.AppendLine("                || consoleWindow == null)");
            builder.AppendLine("            {");
            builder.AppendLine("                return string.Empty;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            FieldInfo activeTextField = consoleWindowType.GetField(");
            builder.AppendLine("                \"m_ActiveText\",");
            builder.AppendLine("                BindingFlags.Instance | BindingFlags.NonPublic);");
            builder.AppendLine();
            builder.AppendLine("            return activeTextField?.GetValue(consoleWindow)");
            builder.AppendLine("                       as string");
            builder.AppendLine("                   ?? string.Empty;");
            builder.AppendLine("        }");

            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}