using System.IO;
using System.Text;
using UnityEditor;

namespace PJDev.DevelopKit.BasicTemplate.Editors
{
    /// <summary>CDebug 콘솔 더블클릭 시 호출부로 이동하는 Editor 스크립트를 생성합니다.</summary>
    public static class CDebugConsoleNavigationGenerator
    {
        public const string GeneratedFileName = "CDebugConsoleNavigation.Generated.cs";

        public static void Generate()
        {
            string directory = CDebugPaths.EditorGeneratedFolder;
            if (!Directory.Exists(directory))
                Directory.CreateDirectory(directory);

            string path = CDebugPaths.ConsoleNavigationGeneratedFilePath;
            string content = BuildSource();
            if (File.Exists(path) && File.ReadAllText(path) == content)
                return;

            File.WriteAllText(path, content, Encoding.UTF8);
            AssetDatabase.ImportAsset(path);
        }

        private static string BuildSource()
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated by CDebugConsoleNavigationGenerator>");
            builder.AppendLine("// Do not edit manually.");
            builder.AppendLine();
            builder.AppendLine("using System;");
            builder.AppendLine("using System.IO;");
            builder.AppendLine("using System.Reflection;");
            builder.AppendLine("using System.Text.RegularExpressions;");
            builder.AppendLine("using UnityEditor;");
            builder.AppendLine("using UnityEditor.Callbacks;");
            builder.AppendLine("using UnityEditorInternal;");
            builder.AppendLine("using UnityEngine;");
            builder.AppendLine();
            builder.AppendLine("namespace PJDev.DevelopKit.BasicTemplate.Editors.Generated");
            builder.AppendLine("{");
            builder.AppendLine("    internal static class CDebugConsoleNavigationGenerated");
            builder.AppendLine("    {");
            builder.AppendLine("        private const string LoggerName = \"CDebug\";");
            builder.AppendLine("        private const string LoggerScriptFileName = \"CDebug.cs\";");
            builder.AppendLine();
            builder.AppendLine("        [OnOpenAsset(0)]");
            builder.AppendLine("#if UNITY_6000_2_OR_NEWER");
            builder.AppendLine("        public static bool OnOpenAsset(EntityId instanceID, int line)");
            builder.AppendLine("#else");
            builder.AppendLine("        public static bool OnOpenAsset(int instanceID, int line)");
            builder.AppendLine("#endif");
            builder.AppendLine("        {");
            builder.AppendLine("#if UNITY_6000_2_OR_NEWER");
            builder.AppendLine("            UnityEngine.Object target = EditorUtility.EntityIdToObject(instanceID);");
            builder.AppendLine("#else");
            builder.AppendLine("            UnityEngine.Object target = EditorUtility.InstanceIDToObject(instanceID);");
            builder.AppendLine("#endif");
            builder.AppendLine("            if (target == null || target.name != LoggerName)");
            builder.AppendLine("                return false;");
            builder.AppendLine();
            builder.AppendLine("            string assetPath = AssetDatabase.GetAssetPath(instanceID);");
            builder.AppendLine("            if (string.IsNullOrEmpty(assetPath)");
            builder.AppendLine("                || !assetPath.Replace('\\\\', '/').EndsWith(\"/\" + LoggerScriptFileName, StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("                return false;");
            builder.AppendLine();
            builder.AppendLine("            string stackTrace = GetConsoleStackTrace();");
            builder.AppendLine("            if (string.IsNullOrEmpty(stackTrace))");
            builder.AppendLine("                return false;");
            builder.AppendLine();
            builder.AppendLine("            return TryOpenCallerFromStackTrace(stackTrace);");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static bool TryOpenCallerFromStackTrace(string stackTrace)");
            builder.AppendLine("        {");
            builder.AppendLine("            MatchCollection matches = Regex.Matches(stackTrace, @\"\\(at\\s+(.+?):(\\d+)\\)\", RegexOptions.IgnoreCase);");
            builder.AppendLine("            for (int i = 0; i < matches.Count; i++)");
            builder.AppendLine("            {");
            builder.AppendLine("                Match match = matches[i];");
            builder.AppendLine("                if (!match.Success)");
            builder.AppendLine("                    continue;");
            builder.AppendLine();
            builder.AppendLine("                string path = match.Groups[1].Value.Replace(\" \", \"\");");
            builder.AppendLine("                if (path.EndsWith(LoggerScriptFileName, StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("                    continue;");
            builder.AppendLine();
            builder.AppendLine("                if (!int.TryParse(match.Groups[2].Value, out int callerLine))");
            builder.AppendLine("                    continue;");
            builder.AppendLine();
            builder.AppendLine("                string fullPath = BuildFullPath(path);");
            builder.AppendLine("                if (string.IsNullOrEmpty(fullPath))");
            builder.AppendLine("                    continue;");
            builder.AppendLine();
            builder.AppendLine("                InternalEditorUtility.OpenFileAtLineExternal(fullPath, callerLine);");
            builder.AppendLine("                return true;");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            return false;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static string BuildFullPath(string path)");
            builder.AppendLine("        {");
            builder.AppendLine("            path = path.Replace('\\\\', '/');");
            builder.AppendLine("            if (Path.IsPathRooted(path))");
            builder.AppendLine("                return path;");
            builder.AppendLine();
            builder.AppendLine("            const string assetsRoot = \"Assets/\";");
            builder.AppendLine("            if (!path.StartsWith(assetsRoot, StringComparison.OrdinalIgnoreCase))");
            builder.AppendLine("            {");
            builder.AppendLine("                int assetsIndex = path.IndexOf(assetsRoot, StringComparison.OrdinalIgnoreCase);");
            builder.AppendLine("                if (assetsIndex >= 0)");
            builder.AppendLine("                    path = path.Substring(assetsIndex);");
            builder.AppendLine("            }");
            builder.AppendLine();
            builder.AppendLine("            string projectRoot = Application.dataPath.Substring(0, Application.dataPath.Length - \"Assets\".Length);");
            builder.AppendLine("            return projectRoot + path;");
            builder.AppendLine("        }");
            builder.AppendLine();
            builder.AppendLine("        private static string GetConsoleStackTrace()");
            builder.AppendLine("        {");
            builder.AppendLine("            Type consoleWindowType = Type.GetType(\"UnityEditor.ConsoleWindow,UnityEditor\");");
            builder.AppendLine("            if (consoleWindowType == null)");
            builder.AppendLine("                return string.Empty;");
            builder.AppendLine();
            builder.AppendLine("            FieldInfo consoleField = consoleWindowType.GetField(");
            builder.AppendLine("                \"ms_ConsoleWindow\", BindingFlags.Static | BindingFlags.NonPublic);");
            builder.AppendLine("            if (consoleField?.GetValue(null) is not EditorWindow consoleWindow || consoleWindow == null)");
            builder.AppendLine("                return string.Empty;");
            builder.AppendLine();
            builder.AppendLine("            FieldInfo activeTextField = consoleWindowType.GetField(");
            builder.AppendLine("                \"m_ActiveText\", BindingFlags.Instance | BindingFlags.NonPublic);");
            builder.AppendLine("            return activeTextField?.GetValue(consoleWindow) as string ?? string.Empty;");
            builder.AppendLine("        }");
            builder.AppendLine("    }");
            builder.AppendLine("}");

            return builder.ToString();
        }
    }
}
